### ISSUE TITLE
texture for crops not showing correctly

### ISSUE THREAD

**Issue by mattybopz** [Joshcraft2002/Dumplings-Delight-Rewrapped#3]
Playing on 1.21.1 Fabric and the texture when the crops from this mod are planted don't show up correctly, wondering if I'm missing a resource pack or dependency or whatnot.

**Comment by Joshcraft2002** [comment]
found the issue, will push a fix shortly

**Comment by Joshcraft2002** [comment]
should now be fixed in the most recent version

it's now out on both modrinth and curseforge
