### ISSUE TITLE
Old Porting Lib version crashing new Farmer's Delight Refabricated update.

### ISSUE THREAD

**Issue by ChrysanthCow** [Joshcraft2002/Dumplings-Delight-Rewrapped#5]
Hi, so you seem to have included an old Porting Lib version in your build. Which overrides the new Porting Lib version in the new Refabricated update due to a change in version schema.

I'd suggest not including Porting Lib, and just letting Farmer's Delight Refabricated's build handle Porting Lib. Apologies for any inconvenience caused by our update, we're still figuring out the rough patches of updating Porting Lib.

**Comment by ChrysanthCow** [comment]
See https://github.com/MehVahdJukaar/FarmersDelightRefabricated/issues/104 for more info on this crash.

**Comment by Joshcraft2002** [comment]
should (hopefully) now be fixed with the most recent version
